### ISSUE TITLE
Implements the playlist system of the site

### ISSUE THREAD

**Issue by antonin-tarrade** [antonin-tarrade/YouLearn#41]
## Task list 
- [ ] Design the add to playlist functionnality on figma
- [ ] Implement the back end logic to create playlists
- [ ] Implement the add to playlist feature on React
